"""empty message

Revision ID: 22494558c8d8
Revises: 
Create Date: 2022-10-11 16:33:54.129052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22494558c8d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id_category', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id_category')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('userstatus', sa.Enum('user', 'pharmacist'), nullable=False),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('medicine',
    sa.Column('id_medicine', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medicine_name', sa.String(length=65), nullable=False),
    sa.Column('manufacturer', sa.String(length=65), nullable=False),
    sa.Column('medicine_description', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('medicine_status', sa.Enum('available', 'pending', 'sold'), nullable=False),
    sa.Column('demand', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id_category'], ),
    sa.PrimaryKeyConstraint('id_medicine')
    )
    op.create_table('order',
    sa.Column('id_order', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=350), nullable=False),
    sa.Column('date_of_purchase', sa.DateTime(), nullable=False),
    sa.Column('shipData', sa.DateTime(), nullable=False),
    sa.Column('order_status', sa.Enum('placed', 'approved', 'delivered'), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_order')
    )
    op.create_table('order_details',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine.id_medicine'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id_order'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_details')
    op.drop_table('order')
    op.drop_table('medicine')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
