"""empty message

Revision ID: 8340ace19878
Revises: 22494558c8d8
Create Date: 2022-11-28 21:03:03.822247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8340ace19878'
down_revision = '22494558c8d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine', sa.Column('quantity', sa.Integer(), nullable=False))
    op.alter_column('order_details', 'medicine_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_details', 'medicine_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('medicine', 'quantity')
    # ### end Alembic commands ###
