"""empty message

Revision ID: a06ee50c3e98
Revises: 8340ace19878
Create Date: 2023-04-26 10:39:17.510484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06ee50c3e98'
down_revision = '8340ace19878'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine', sa.Column('image_url', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicine', 'image_url')
    # ### end Alembic commands ###
