"""empty message

Revision ID: c225a7b00807
Revises: a06ee50c3e98
Create Date: 2023-04-26 15:36:05.328324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c225a7b00807'
down_revision = 'a06ee50c3e98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine', sa.Column('demand_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicine', 'demand_count')
    # ### end Alembic commands ###
